ALTER TABLE coupons ADD COLUMN IF NOT EXISTS title VARCHAR(120) NULL;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS applicable_restaurant_id BIGINT NULL;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS subtitle VARCHAR(300) NULL;
ALTER TABLE banners ADD COLUMN IF NOT EXISTS cta_text VARCHAR(80) NULL;
ALTER TABLE coupons DROP CONSTRAINT IF EXISTS chk_coupons_module;
ALTER TABLE coupons ADD CONSTRAINT chk_coupons_module CHECK (applicable_module IN ('FOOD', 'RIDE', 'MARKETPLACE', 'ALL'));
